=	运维中心
:toc: left
:toclevels: 4

:sectnums:
:sectnumlevels: 5

在项目上方的“运维中心”菜单，可看到本项目内的实时任务、离线任务的基本情况，包括不同状态的实时任务数量，离线任务数量，以及离线任务的一些基本统计信息。

在页面上的“实时任务运维”、“离线任务运维”按钮，分别进入不同的运维管理页面。

==	实时任务运维

实时任务运维模块中可查看实时任务实例的运行状态、查看任务运行日志，同时可以对任务状态进行切换。

* **查看实时任务实例**

在“运维中心”中的“实时任务运维”（或在左侧菜单中的“实时任务运维”），可查看实时任务名称、运行状态、责任人、最近操作人等信息。

* **查看日志**

通过任务列表中的“日志”链接，可查看本任务的日志信息。

* **实时任务的状态切换**

. 运行->停止：对正在运行的任务，在操作栏点击“停止”按钮，此任务即停止运行。
. 停止->运行：对停止状态的任务，在操作栏点击“恢复”按钮此任务即恢复运行。
. 失败->重试：对于失败状态的任务，可以点击“重试”，任务会再次尝试提交运行。

==	离线任务运维
离线任务的运维包括2大部分：任务管理、任务运维。任务管理模块中显示所有离线任务的信息，并可进行补数据操作。任务运维模块中显示所有离线任务实例的运行状态、可查看任务运行日志、查看任务上下游依赖关系，同时可以对任务状态进行切换。

[[jobManagement]]
===	任务管理

* **查看任务信息**

点击“运维中心”左侧菜单中的“离线任务运维->任务管理”，可查看离线任务列表，包括任务名称、调度周期、任务类型、责任人、调度生效周期、具体调度时间、最近修改时间等信息。

* **修改**

在任务管理列表右侧的操作栏，点击“修改”按钮后，页面会进入此任务的编辑页面。

* **补数据**

在任务管理列表右侧的操作栏，点击“修改”按钮后，在弹窗中填写如下信息：

. 补数据名称；
. 业务日期：选择业务日期的开始日期、结束日期；
. 选定任务：在列出的各任务中选定需要进行补数据的任务；

点击“运行选中任务”后，系统会提示“补数据任务已在执行中，点击下方按钮查看结果”，点击后，可以在任务运维页面的“补数据”标签页内查看补数据任务的运行情况。

===	任务运维

* **查看任务实例信息**

点击“运维中心”左侧菜单中的“离线任务运维->任务运维”，可查看离线任务实例列表，包括任务名称、调度周期、任务类型、业务日期、调度时间、任务实例创建时间、任务实例执行的开始时间、结束时间、运行时长、运行状态等信息。

任务实例列表还可以根据业务日期、责任人、任务名称、状态进行搜索和筛选。

* **查看任务间的依赖关系（流程）**

在任务运维页面，任务实例列表的操作栏点击“流程”按钮，显示选中任务及其上下游的任务实例依赖关系。

在依赖关系图中，选中某个任务，点击右键菜单，可对此任务执行以下操作：

. 展开上游（6层）：点击后，直接展开选中任务的6层上游任务；
. 展开下游（6层）：类似“展开上游（6层）”；
. 查看任务日志：点击后，进入离线任务日志查看页面；
. 编辑任务：点击后，进入离线任务编辑页面；
. 查看任务属性：点击后，弹出任务属性弹窗，弹窗中包括任务名称、任务ID等属性信息；
. 终止：即手动杀任务的功能，点击后，本依赖关系图刷新任务状态；
. 刷新任务实例：点击后，刷新页面显示的所有任务实例，本依赖关系图刷新任务状态；
. 重跑并恢复调度：点击后，执行重跑，并恢复任务调度，本依赖关系图刷新任务状态；
. 置成功并恢复调度：点击后，强制将此设置为成功执行（状态为：手动设置成功），并恢复本任务的调度；
. 重跑下游并恢复调度：点击后，对下游任务进行重跑，并恢复任务调度，本依赖关系图刷新任务状态；

对于右键菜单中的6~9项操作，不同的任务状态可进行不同的操作：

[cols="1, 4", options="header"]]
|===
|任务状态  |可进行的操作
|未运行 |重跑任务
|运行中 |杀任务
|成功 |跑任务
|失败 |跑任务、置成功并恢复调度
|===

* **查看任务执行日志**

在任务运维页面，任务实例列表的操作栏点击“日志”按钮，页面显示本任务实例的执行日志信息。

* **批量杀任务、批量重跑任务**

在任务运维页面，任务实例列表中可复选多个任务，选中后，点击页面左上角的“批量杀任务”或“批量重跑任务”后，可杀掉多个任务实例，或对多个任务实例执行重跑操作。

NOTE: 不同的任务状态可进行不同的操作，若您选中的任务包含了不同的状态，可能导致不能进行统一操作，需要重新选择任务。


==	告警监控

告警监控模块中保存了RD-OS产生的所有实时、离线任务告警信息，同时支持用户自定义告警规则，配置成功后，当监控的任务触发了告警规则后，RD-OS将以邮件或短信的形式通知相关人员。

点击某项目上方的“运维中心”菜单，并在左侧的“告警监控”菜单下，可进入告警记录和自定义告警功能。

===	告警记录

告警记录中包括了系统产生的所有任务告警信息，可在实时或离线标签页中查看两类任务产生的告警数量、任务名称、任务类型、责任人等信息。

可筛选时间、任务、告警接收人等信息筛选特定的告警。


===	自定义告警

自定义告警可分别针对实时任务和离线任务配置不同的告警规则，可查看、修改已配置的规则，同时可对告警规则进行打开或关闭。

自定义告警模块依然按照实时任务和离线任务两个标签页展示，但二者操作方式类似，下面统一说明：

* **创建告警规则**
点击告警规则列表右上角的“创建告警规则”，在弹窗中完善如下信息：

. 告警规则名称；
. 任务名称；
. 告警触发点：
.. 实时任务只有“失败”一个触发点；
.. 离线任务可选择“任务失败”、“未完成”、“任务停止”、“定时”中的一种。
... 任务失败、任务停止：任务出错失败或任务停止时通知相关责任人。
... 未完成：若对任务执行时间有预期，可选择“未完成”，输入任务运行时长后，若此任务执行时长超过了设定值，RD-OS会通知责任人。
... 定时：若对任务的启动时间、执行完成时间有预期，输入定时时间后，若此任务超过了定时时间未完成，RD-OS会通知责任人。
. 告警方式：支持邮件、短信；
. 告警接收人：可选择此任务的责任人或项目组内的其他人员；

* **告警规则的开启、关闭**

开启某告警规则，表示RD-OS会按照用户设定的规则产生并发送告警。

关闭某告警规则，通常用于暂时不想应用此告警规则，但也不想删除，以后可能再次开启的情况。
