[[DataMang]]
= 数据管理
//文档整体配置
include::99_documentSetting.adoc[]


DTinsightIDE数据管理模块中可以看到平台内表的元数据信息详情、数据生命周期管理、脏数据管理等操作。

[NOTE]
本版本的DTinsightIDE不支持表级、字段级的数据访问权限控制。

[NOTE]
数据管理模块的很多项数据都有一定时间的延迟，例如血缘信息的变更，变更后可能无法立即体现在页面上。

[[datamang_tablemanag]]
== 表管理

可进入**数据管理-表管理**页面，对本项目空间内的数据表进行搜索。在全部数据页面中，通过选择数据类目导航+搜索框中输入表名进行模糊匹配的方式快速查找需要的表。

[[datamang_tablemanag_view]]
=== 查看表

点击**表管理**模块中任意列表中的数据表名称，即可跳转至表详情页面，包括表的基本信息、存储信息、字段信息、分区信息、血缘信息和数据预览。

* **表的基本信息**

表的基本信息包括所属项目、表名、创建者、创建时间、所属类目、描述。

可单击**生成建表语句**按钮生成该表的建表语句。

* **表的存储信息**

表的存储信息包括物理存储量（数据存在延迟）、生命周期、是否分区表、表创建时间、DDL最后变更时间和最后数据变更时间。

* **表的字段信息**

表的字段信息包括字段名称、类型、是否分区字段和描述。

* **表的分区信息**

通过表的分区信息模块可查看表当前的分区，包括分区名、创建时间、存储量。

* **表的数据预览**

通过表的数据预览模块可预览当前表的数据信息。

* **表的血缘信息**

通过表的血缘信息模块可查看该表数据流DTinsightIDE的血缘信息，只支持表级血缘分析。

[[datamang_tablemanag_tablemanag]]
=== 数据表的管理

在数据表管理中，可以对表进行以下操作：生命周期设置、表管理（包括修改表的类目、描述、字段、分区等）、表删除等。

* **表的管理操作**

点击**数据管理-表管理**模块中点击**编辑**，即进入表的管理页面。

在表的管理页面，支持以下操作：

. 修改表的所属类目
. 修改表的生命周期
. 修改表的描述
. 修改表结构
.. 新增字段
.. 移动新增字段的位置（只能在新增字段中移动，不会影响已有字段）
. 删除表：数据表一旦删除，该表的结构信息及表的所有数据均不可恢复，请谨慎操作。

[[datamang_tablemanag_create]]
=== 新建表

通常情况下，数据开发过程中需要创建表来存储数据同步、数据加工的结果数据，数据管理模块提供可视化建表、语句建表两种方式创建表。

* **可视化建表**

单击顶部菜单栏中的**数据管理-表管理**，单击**新建表**，填写新建表弹出框中的各配置项。

配置项说明：

. 表名：以字母、数字、下划线组成，具体请遵循Hive建表的表名约束规则。
. 分隔符：可以不填写，不填写时默认为Hive的默认建表分隔符：/u0001。
. 类型：内部表、外部表，如果选择外部表，则需要指定外部表的目录地址。
. 所属类目：当前表所处的类目，类目导航配置详见<<datamang_cate>>。
. 生命周期：即DTinsightIDE的生命周期功能。填写一个数字表示天数，那么该表（或分区）超过一定天数未更新的数据会被清除。支持3天、7天、30天、90天、365天、自定义多种选项。
. 存储格式：支持textfile或orc格式，这2种格式的详细区别请参考
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-CreateTableCreate/Drop/TruncateTable[Hive官方文档]
. 描述：当前表的简要说明。

单击**下一步**，填写新建表页面中填写字段和分区信息的各配置项，主要是添加字段信息和分区信息。

配置项说明：

. 字段名：字段英文名，由字母、数字、下划线组成。
. 字段类型：Hive数据类型，详细请参考
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-CreateTableCreate/Drop/TruncateTable[Hive官方文档]
. 注释：字段详细描述。
. 操作：上移、下移、删除。
. 配置分区键的具体信息，支持string和bigint类型。

单击**提交**。新建表提交成功后，系统将自动跳转返回数据表管理界面，单击**表管理**即可查看新建表。


* **语句建表**

单击顶部菜单栏中的**数据管理**，导航至**表管理**，单击**DDL建表**。

填写Hive SQL建表语句，建表的语法请参考
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-CreateTableCreate/Drop/TruncateTable[Hive官方文档]，单击**确定**，完成建表。

[NOTE]
建表中的各项信息本质上是遵循Hive建表的方式。

[[datamang_record]]
== 操作记录

DTinsightIDE记录了每个表的DDL操作语句，并形成每个表的操作记录。点击**数据管理-操作记录**后，根据表名搜索，点击后有右侧面板弹出，显示此表的DDL操作记录。

支持对变更时间、操作人、变更语句的筛选和搜索。

[NOTE]
如果此表已被删除，DTinsightIDE依然会保留此表的操作记录，但在表名后备注已删除的信息

[[datamang_cate]]
== 数据类目

构建数据类目体系，便于数据维护。数据类目体系是树形结构的，每张表可以关联到唯一的一个叶子节点， 便于您进行数据检索与数据维护。

单击**数据管理-数据类目**页面。

. 单击表所属类目设置后的“添加”icon，添加下一级类目。除根节点外，最高可支持四级类目的设置。
. 单击表所属类目设置后的“编辑”icon，修改类目名称。
. 单击表所属类目设置后的“删除”icon，删除此类目。

[[datamang_dirtydata]]
== 脏数据管理

在数据同步执行的过程中可能会出现因主键冲突、格式转换错误等各种原因造成部分数据无法正常写入，不能被正常写入的数据被称为“脏数据”。

DTinsightIDE支持对脏数据的配置、保存和管理

[[datamang_dirtydata_config]]
=== 脏数据的配置

在**数据同步**任务的**通道控制**步骤中，可配置是否需要记录脏数据，并可指定存储脏数据的表名、生命周期。

DTinsightIDE同时支持错误数据比例的配置，当任务结束后，系统对错误数据的占比进行统计，超过设定的阈值时，此任务被置为失败。

[[[datamang_dirtydata_view]]]
=== 脏数据的查看

在**任务管理-脏数据管理**模块中可以查看脏数据的产生趋势、产生脏数据最多的任务，以及每一张产生脏数据表的情况。

* **脏数据产生趋势**

选中某个任务后，可以查看此任务在最近一段时间产生脏数据的数量，支持最近3天、7天、30天、60天的数据查看。

* **脏数据产生TOP30任务**

通过观察产生脏数据数量较大的任务，可以针对性的排查此任务的配置信息、源数据库的数据质量等问题，及时解决问题。

* **脏数据表管理**

脏数据表的管理与普通数据表管理类似，区别在于以下几个方面：

. 相关任务：列出此表对应的任务名称，方便排查任务信息；
. 脏数据概览：展现最近一段时间此表的脏数据量趋势；
. 原因分析：系统对脏数据造成的异常自动统计，原因有：空指针、主键冲突、类型转换、其他4种，如果某类原因占比较大，您可以通过对源数据库的数据进行针对性的分析；

[NOTE]
脏数据产生原因是“空指针”，并不是说脏数据本身是空指针，而是由于脏数据造成同步任务程序出现了空指针异常。
